### ISSUE TITLE
not matching string if it is at the end of the file

### ISSUE THREAD

**Issue by ebrandel** [DissectMalware/yaradbg-issues#1]
example rule:

```
rule find_asdfasdf {
  strings:
    $s1 = "asdfasdf"
  condition:
    all of them
}
```

won't match on:

```
asdfasdf
```

But will match on:

```
asdfasdf tacos
```

![image](https://user-images.githubusercontent.com/1231380/154755574-6a35201f-1afd-4452-b137-136005bcc177.png)

![image](https://user-images.githubusercontent.com/1231380/154755615-cdfa3332-0e20-410b-baf3-043ded4092de.png)

**Comment by DissectMalware** [comment]
when a regex/string/hex string matched at the end of the file content, the code couldn't match it as the last bytecode (match) was skipped.

The bug is fixed now.
![image](https://user-images.githubusercontent.com/9646319/154789508-2b193898-2bee-4266-bce0-b6135fc468b5.png)


I can see a UI issue there but I prefer to close this one and address the UI issue in a separate issue.

Thank you very much for testing the app and reporting the issue. It meant a lot.

Please keep posting issues!
